### ISSUE TITLE
Support newer Laravel version?

### ISSUE THREAD

**Issue by hms5232** [antriver/laravel-multi-cache#1]
Hi, I recently face dual cache problem, but Laravel doesn't bulid in this feature. I had every intention of developing a package to do this (dual-cache, but changed to multi cache after planning a while). Google search lead me to here (The package name is exactly the same. Great minds think alike😇). 

Everything is good, but package current not support version after 5. Maybe can add support to Laravel 8 or later?
Thanks.

BTW, if repo can be added `LICENSE`, it will more friendly to use 😀

**Comment by hms5232** [comment]
I have developed another package to fit my need: https://github.com/hms5232/laravel-twin-cache

Thanks.

**Comment by antriver** [comment]
This is a very late reply sorry.

I've released a new version compatible with Laravel 10: https://packagist.org/packages/antriver/laravel-multi-cache#10.0.0

Glad to hear you solved it in the meantime though.
