### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by dramamask** [antriver/laravel-multi-cache#2]
I was just about to start writing a "dual cache" driver for Laravel when I came across your multi-cache package here. This is exactly what I need. Are you planning on making this package available for use with Laravel 11?

**Comment by antriver** [comment]
Hi @dramamask 

Yep that is on the to-do list. It currently works with Laravel 10 so I don't see why it wouldn't work with 11 with a small tweak. I couldn't give you an ETA currently, but feel free to make a PR if you find the time.

Thanks
