### ISSUE TITLE
Restrict get function from making put operations

### ISSUE THREAD

**Issue by gabriel-vasile** [antriver/laravel-multi-cache#3]
Hi, this package looks perfect for my use case but there is one problem inside `get` function:

https://github.com/antriver/laravel-multi-cache/blob/7f8b0e2bb789af507629660856d12ee14c4dba8c/src/MultiStore.php#L89-L112

Calling `get` will try to synchonize the key to `missedStores`. This behaviour is not needed in my case, especially with the hard-coded expire of 1 day.

My question is: are you willing to accept a PR adding a config flag that turns on/off this behaviour?

**Comment by antriver** [comment]
Hi,
This sounds like a very sensible option to add. Feel free to make a PR 🙂
